app:
  host: "0.0.0.0"
  port: 5001

database:
  host: "127.0.0.1"
  port: "3306"
  config: "parseTime=true&loc=Asia%2FShanghai"
  db-name: "yunyi"
  username: "root"
  password: "ossdbg1"
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: ""
  log-zap: false

# redis configuration
redis:
  addr: 127.0.0.1:6379
  password: "admin@2024"
  db: 0

jwt:
  access-signed-key: X7Y9Z2A4CCC8D0E2F4G6H8I0J224L6M8N0P2Q4R6S8T0U2V4W6X8Y0Z2
  refresh-signed-key: X7Y9Z2A4B6C8DEE2F4G6H8I7J2K4L6M8N7P2Q4R6S8T7U2V4W6X8Y0Z2
  expires-time: 7d
  buffer-time: 1d
  issuer: yunyi

# captcha configuration
captcha:
  key-long: 6
  img-width: 240
  img-height: 80
  open-captcha: 0 # 0代表一直开启，大于0代表限制次数
  open-captcha-timeout: 3600 # open-captcha大于0时才生效

# zap logger configuration
zap:
  level: info
  format: console
  prefix: "[yunyi]"
  director: log
  show-line: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true
  retention-day: 7
