app:
  host: "0.0.0.0"
  port: 5001

database:
  host: "127.0.0.1"
  port: "3306"
  config: "parseTime=true&loc=Asia%2FShanghai"
  db-name: "yunyi"
  username: "root"
  password: "ossdbg1"
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: ""
  log-zap: false

jwt:
  signing-key: qmPlus
  expires-time: 7d
  buffer-time: 1d
  issuer: qmPlus

# captcha configuration
captcha:
  key-long: 6
  img-width: 240
  img-height: 80
  open-captcha: 0 # 0代表一直开启，大于0代表限制次数
  open-captcha-timeout: 3600 # open-captcha大于0时才生效
